#!/usr/bin/env python3
"""
Canon Index Generator

Scans canon/ directory for all artifacts, generates INDEX.md with categorized
artifact list and creates artifacts.json with metadata.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List

import yaml


def load_artifact(file_path: Path) -> Dict:
    """Load and parse a Canon artifact YAML file."""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Extract YAML frontmatter
        if content.startswith('---'):
            parts = content.split('---', 2)
            if len(parts) >= 3:
                frontmatter = yaml.safe_load(parts[1])
                body = parts[2].strip()
                
                # Calculate word count
                word_count = len(body.split())
                
                return {
                    'path': str(file_path.relative_to(file_path.parent.parent)),
                    'filename': file_path.name,
                    'id': frontmatter.get('id', 'unknown'),
                    'title': frontmatter.get('title', 'Untitled'),
                    'type': frontmatter.get('type', 'unknown'),
                    'created_at': frontmatter.get('created_at', ''),
                    'updated_at': frontmatter.get('updated_at', ''),
                    'author': frontmatter.get('author', 'unknown'),
                    'parent': frontmatter.get('parent'),
                    'trace_id': frontmatter.get('trace_id'),
                    'status': frontmatter.get('status', 'draft'),
                    'word_count': word_count,
                    'frontmatter': frontmatter,
                    'body_preview': body[:200] + '...' if len(body) > 200 else body
                }
    except Exception as e:
        print(f"::warning::Failed to load artifact {file_path}: {e}")
        return None


def find_canon_artifacts(canon_dir: Path) -> List[Dict]:
    """Find all Canon artifacts in the directory."""
    artifacts = []
    
    if not canon_dir.exists():
        print(f"::warning::Canon directory {canon_dir} does not exist")
        return artifacts
    
    for file_path in canon_dir.rglob('*.md'):
        # Skip INDEX.md and README.md
        if file_path.name in ['INDEX.md', 'README.md']:
            continue
        
        artifact = load_artifact(file_path)
        if artifact:
            artifacts.append(artifact)
    
    return artifacts


def categorize_artifacts(artifacts: List[Dict]) -> Dict[str, List[Dict]]:
    """Categorize artifacts by type."""
    categories = {
        'foundational': [],
        'channel': [],
        'closure': [],
        'governance': [],
        'unknown': []
    }
    
    for artifact in artifacts:
        artifact_type = artifact.get('type', 'unknown')
        if artifact_type in categories:
            categories[artifact_type].append(artifact)
        else:
            categories['unknown'].append(artifact)
    
    # Sort artifacts within each category by ID
    for category in categories:
        categories[category].sort(key=lambda x: x.get('id', ''))
    
    return categories


def generate_index_md(categories: Dict[str, List[Dict]], output_path: Path):
    """Generate INDEX.md file."""
    lines = [
        "# Canon of Closure - Index",
        "",
        f"*Last Updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}*",
        "",
        "This index is automatically generated by the Canon Auto-Merge system.",
        "",
        "## Overview",
        "",
        f"Total Artifacts: {sum(len(artifacts) for artifacts in categories.values())}",
        "",
    ]
    
    # Add statistics by category
    lines.append("### By Category")
    lines.append("")
    for category, artifacts in categories.items():
        if artifacts:
            lines.append(f"- **{category.title()}**: {len(artifacts)} artifact(s)")
    lines.append("")
    
    # Add artifacts by category
    category_descriptions = {
        'foundational': 'Core Canon documents establishing frameworks and principles',
        'channel': 'Communication and integration channels',
        'closure': 'Issue closure documentation and retrospectives',
        'governance': 'Governance, policy, and procedural artifacts',
        'unknown': 'Uncategorized artifacts'
    }
    
    for category, artifacts in categories.items():
        if not artifacts:
            continue
        
        lines.append(f"## {category.title()} Artifacts")
        lines.append("")
        lines.append(category_descriptions.get(category, ''))
        lines.append("")
        
        # Add table
        lines.append("| ID | Title | Status | Created | Author |")
        lines.append("|------|-------|--------|---------|--------|")
        
        for artifact in artifacts:
            artifact_id = artifact.get('id', 'N/A')
            title = artifact.get('title', 'Untitled')
            status = artifact.get('status', 'draft')
            created = artifact.get('created_at', 'N/A')
            author = artifact.get('author', 'unknown')
            path = artifact.get('path', '')
            
            # Create markdown link
            title_link = f"[{title}]({path})"
            
            lines.append(f"| {artifact_id} | {title_link} | {status} | {created} | {author} |")
        
        lines.append("")
    
    # Add footer
    lines.extend([
        "---",
        "",
        "## Maintenance",
        "",
        "This index is automatically updated by the Canon Auto-Merge system when:",
        "- New Canon artifacts are merged",
        "- Existing artifacts are updated",
        "- Manual regeneration is triggered",
        "",
        "For questions or issues, contact the Canon Stewards.",
        ""
    ])
    
    # Write file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f"Generated INDEX.md with {len(lines)} lines")


def generate_artifacts_json(artifacts: List[Dict], output_path: Path):
    """Generate artifacts.json file."""
    metadata = {
        'generated_at': datetime.now(timezone.utc).isoformat(),
        'total_artifacts': len(artifacts),
        'version': '1.0',
        'artifacts': artifacts
    }
    
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(metadata, f, indent=2, ensure_ascii=False)
    
    print(f"Generated artifacts.json with {len(artifacts)} artifacts")


def main():
    parser = argparse.ArgumentParser(description="Canon Index Generator")
    parser.add_argument('--canon-dir', default='canon', help='Canon directory path')
    parser.add_argument('--output-index', help='Output INDEX.md path')
    parser.add_argument('--output-json', help='Output artifacts.json path')
    
    args = parser.parse_args()
    
    print("::group::Canon Index Generation")
    
    # Resolve paths
    repo_root = Path(os.environ.get('GITHUB_WORKSPACE', '.')).resolve()
    canon_dir = (repo_root / args.canon_dir).resolve()
    
    if not canon_dir.exists():
        print(f"::warning::Canon directory does not exist: {canon_dir}")
        print("Creating directory...")
        canon_dir.mkdir(parents=True, exist_ok=True)
    
    # Set output paths
    index_path = Path(args.output_index) if args.output_index else (canon_dir / 'INDEX.md')
    json_path = Path(args.output_json) if args.output_json else (canon_dir / 'artifacts.json')
    
    # Load all artifacts
    print(f"Scanning {canon_dir} for artifacts...")
    artifacts = find_canon_artifacts(canon_dir)
    print(f"Found {len(artifacts)} artifacts")
    
    if not artifacts:
        print("::warning::No artifacts found, generating empty index")
    
    # Categorize artifacts
    categories = categorize_artifacts(artifacts)
    
    # Print summary
    print("\nArtifact Summary:")
    for category, artifact_list in categories.items():
        if artifact_list:
            print(f"  {category.title()}: {len(artifact_list)}")
    
    # Generate outputs
    print(f"\nGenerating INDEX.md at {index_path}...")
    generate_index_md(categories, index_path)
    
    print(f"Generating artifacts.json at {json_path}...")
    generate_artifacts_json(artifacts, json_path)
    
    print("\n✅ Canon index generation complete!")
    print("::endgroup::")
    
    sys.exit(0)


if __name__ == '__main__':
    main()
