#!/bin/bash

# Pi Forge Quantum Genesis - Render Deployment Helper
# This script prints the deployment instructions to your terminal

echo "🚀 Pi Forge Quantum Genesis - Render Deployment Guide"
echo "===================================================="
echo ""
echo "Follow these steps to deploy to Render:"
echo ""
echo "1. 🌐 Go to https://render.com and sign in"
echo "2. 📦 Click 'New' → 'Web Service'"
echo "3. 🔗 Connect your GitHub repository (pi-forge-quantum-genesis)"
echo "4. ⚙️  Configure the service:"
echo "   - Name: pi-forge-backend"
echo "   - Environment: Docker"
echo "   - Branch: main"
echo "   - Dockerfile Path: Dockerfile"
echo ""
echo "5. 🔑 Add Environment Variables:"
echo "   - PORT=8000"
echo "   - PYTHON_VERSION=3.11"
echo "   - DATABASE_URL=postgresql://..."
echo "   - PI_API_KEY=your_pi_api_key"
echo "   - PI_APP_ID=your_pi_app_id"
echo "   (Add other secrets as needed)"
echo ""
echo "6. 🚀 Click 'Create Web Service'"
echo "7. 📊 Monitor the build and deployment"
echo ""
echo "8. ✅ Verify deployment:"
echo "   - Visit https://your-service-name.onrender.com/health"
echo ""
echo "9. 🔄 Update Vercel Frontend:"
echo "   - Set NEXT_PUBLIC_BACKEND_URL=https://your-service-name.onrender.com"
echo ""
echo "📖 For detailed instructions, see docs/RENDER_SETUP.md"
echo ""
echo "⚠️  Note: If your Next.js frontend uses 'output: export' in next.config.mjs,"
echo "   remove it to enable API routes like /api/sponsor-transaction."