# GitHub Actions workflow (copy to `.github/workflows/link-check.yml` to enable)

name: Link Checker

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC
  workflow_dispatch: {}

jobs:
  link-check:
    name: Run link check
    runs-on: ubuntu-latest
    env:
      LINK_CHECK_SITE: "https://quantumpiforge.com/"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 tqdm

      - name: Run link checker
        run: |
          python tools/link_check.py "$LINK_CHECK_SITE" --workers 16 --output link_check_results.csv

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: link-check-results
          path: link_check_results.csv
